rails generate model cdosysmail_failures
rails generate model lss_clients
rails generate model lss_clients2
rails generate model lss_fname
rails generate model lss_jobs
rails generate model lss_terp
rails generate model lss_terplang
rails generate model tblbilledjobstemp
rails generate model tblbillinggroups
rails generate model tblbillingrates
rails generate model tblbillingrules
rails generate model tblcertifications
rails generate model tblclient
rails generate model tblclient_b
rails generate model tblclientbackup010809
rails generate model tblclientio
rails generate model tblclientnotes
rails generate model tblcommissionrates
rails generate model tblemployeestatus
rails generate model tblevent
rails generate model tblgeo
rails generate model tblinterplang
rails generate model tblinterpreters
rails generate model tblinterpreterservice
rails generate model tblinterpsessions
rails generate model tblinvoicecycles
rails generate model tblinvoicelines
rails generate model tblinvoices
rails generate model tblinvoicetemp
rails generate model tblinvparameters
rails generate model tbljobsclosedtmp
rails generate model tbljobtemp
rails generate model tbljobviews
rails generate model tbllanguages
rails generate model tbllineitems
rails generate model tbllocations
rails generate model tblnextinvoice
rails generate model tbloffices
rails generate model tblofficesettings
rails generate model tblpaygroups
rails generate model tblpayrates
rails generate model tblpayrules
rails generate model tblpersonalsched
rails generate model tblplaces
rails generate model tblreminders
rails generate model tblreportoptions
rails generate model tblreportparams
rails generate model tblrequestedinterpreter
rails generate model tblrptuserlog
rails generate model tblsalesreps
rails generate model tblschedstatus
rails generate model tblscheduleassignments
rails generate model tblscheduleassignmentslog
rails generate model tblservicecode
rails generate model tblservicegroup
rails generate model tblservicesfor
rails generate model tblsessions
rails generate model tblshifttimes
rails generate model tblskillassign
rails generate model tblskills
rails generate model tbltaxrates
rails generate model tblterms
rails generate model tblusergroups
rails generate model tblusers
rails generate model tblversions
rails generate model temp_mailinglist
