source 'https://rubygems.org'
gem 'rails', '>= 3.2.7'
gem 'sqlite3', :group => [:development, :test]
gem 'mysql2'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier'
  gem 'less'
  gem 'therubyracer', :platform => :ruby
end
gem 'jquery-rails'
gem "puma", ">= 1.6.1", :group => :production
gem "rspec-rails", ">= 2.11.0", :group => [:development, :test]
gem "capybara", ">= 1.1.2", :group => :test
gem "email_spec", ">= 1.2.1", :group => :test
gem "cucumber-rails", ">= 1.3.0", :group => :test, :require => false
gem "database_cleaner", ">= 0.8.0", :group => :test
gem "launchy", ">= 2.1.2", :group => :test
gem "factory_girl_rails", ">= 4.0.0", :group => [:development, :test]
gem "bootstrap-sass", ">= 2.0.4.0"
gem "devise", ">= 2.1.2"
gem "cancan", ">= 1.6.8"
gem "rolify", ">= 3.2.0"
gem "yard", :group => [:development, :test]
gem 'simplecov', :require => false, :group => :test
gem 'awesome_print', :group => [:development]
gem "rails-erd", :group =>[:development]

## Useful gems from other Mike projects
gem "omniauth", ">= 1.0.0"
gem 'omniauth-facebook', '~> 1.4.0'
gem 'oauth2'
gem "bootstrap_forms"
gem 'bootstrap-datepicker-rails'
gem 'rails_admin' # rather than scaffold generate CRUD, use this
gem 'country_select'
gem 'kaminari' # pagination
gem 'carrierwave' # upload handling
gem 'mime-types' # used with uploading
gem 'mini_magick' # image manipulation
gem 'geocoder' # autopopulate lat/lon from address, useful geo functions
gem 'money-rails' # handle money math, formatting, conversions
gem 'enumerated_attribute'  # easy enum types
gem "debugger", :group => :development

